# Configuration for MARL Environment
grid_size:
  X: 281         # Width of the grid
  Y: 500         # Height of the grid
  D: 4           # Number of layers in the grid (e.g., environment, targets, jammers, agent positions)

pixel_scale: 2
obs_range: 5  

map_path: '/Users/hamishmacintosh/Uni Work/METR4911/Shared Repo/Shared-MARL-Env/city_image_1.npy'

n_agents: 10     # Number of agents in the environment
n_targets: 15    # Number of targets in the environment
n_jammers: 5     # Number of jammers in the environment
jamming_radius: 7 # Radius of jamming effect from each jammer

seed: 1
