# Configuration for MARL Environment
grid_size:
  #X: 100         # Width of the grid - UNNEEDED - get from map
  #Y: 177        # Height of the grid - UNNEEDED - get from map
  D: 4           # Number of layers in the grid (e.g., environment, targets, jammers, agent positions)

pixel_scale: 4 #Going down reduces the pixel_size, which reduces the map
map_scale: 0.18 #Going up makes to map larger

obs_range: 17 #13
comm_range: 40 #10 ---- this is actually diameter 
agent_type: 'discrete'
#agent_type: 'continuous'

map_path: 'city_image_1.npy'
#map_path: 'city_image_2.npy'
#map_path: 'city_image_3.npy'

n_agents: 5
n_targets: 10
n_jammers: 3
jamming_radius: 20 #This is radius, in comparison to comms_range. That is why it is a smaller value then comms_range, but looks bigger relitivly.  

seed: 9

# Example locations
#agent_positions:
#  - [17, 39]
#  - [71, 17]
#  - [23, 37]
#  - [31, 13]
#  - [61, 19]
#target_positions:
# - [18, 39]
#jammer_positions:
#  - [0, 0]

jammer_discovery_reward: 50
target_discovery_reward: 100
tracking_reward: 10
destruction_reward: 300
movement_penalty: -1
exploration_reward: 5