# Configuration for MARL Environment
grid_size:
  #X: 100         # Width of the grid - UNNEEDED - get from map
  #Y: 177        # Height of the grid - UNNEEDED - get from map
  D: 4           # Number of layers in the grid (e.g., environment, targets, jammers, agent positions)

pixel_scale: 20
map_scale: 0.05

obs_range: 5
comm_range: 10

map_path: 'city_image_1.npy'

n_agents: 5
n_targets: 10
n_jammers: 3
jamming_radius: 15

seed: 1

# Example locations
agent_positions:
  - [17, 39]
  - [71, 17]
  - [23, 37]
  - [31, 13]
  - [61, 19]
#target_positions:
#  - [1000, 1000]
#jammer_positions:
#  - [0, 0]

jammer_discovery_reward: 50
target_discovery_reward: 100
tracking_reward: 10
destruction_reward: 300
movement_penalty: -1
exploration_reward: 5