# Configuration for MARL Environment
grid_size:
  X: 50          # Width of the grid
  Y: 50          # Height of the grid
  D: 1           # Number of layers in the grid (e.g., environment, targets, jammers, agent positions)

resolution: 30
obs_range: 5  

map_path: 'city_image_1.npy'

n_agents: 10     # Number of agents in the environment
n_targets: 3    # Number of targets in the environment
n_jammers: 5     # Number of jammers in the environment
jamming_radius: 7 # Radius of jamming effect from each jammer

seed: 1