env: custom_multi_agent_env
env_config:
  config_path: "config.yaml"
  ae_folder_path: "/media/rppl/T7 Shield/METR4911/TA_autoencoder_h5_data/AE_save_06_09"

num_workers: 1
framework: torch
# lr: 1e-4
# train_batch_size: 1
# sgd_minibatch_size: 1
# num_sgd_iter: 1
# rollout_fragment_length: 1
# sample_timeout_s: 350
# batch_mode: complete_episodes
# num_gpus: 1
# reuse_actors: True

model:
  # use_lstm: True
  fcnet_hiddens: [1024, 1024]
  fcnet_activation: relu
  vf_share_layers: True

local_dir: "./custom_ray_results"

multiagent:
  policies:
    policy_0:
      - None
      - Box
      - [-inf, inf]
      - [1024]  # Flattened observation space
      - {}  # Modify action space if necessary
    # policy_1: # Uncomment these for training a policy per agent
    #   - None
    #   - Box
    #   - [-inf, inf]
    #   - [1280]  # Flattened observation space
    #   - {}
    # policy_2:
    #   - None
    #   - Box
    #   - [-inf, inf]
    #   - [1280]  # Flattened observation space
    #   - {}
    # policy_3:
    #   - None
    #   - Box
    #   - [-inf, inf]
    #   - [1280]  # Flattened observation space
    #   - {}
    # policy_4:
    #   - None
    #   - Box
    #   - [-inf, inf]
    #   - [1280]  # Flattened observation space
    #   - {}
    # policy_5:
    #   - None
    #   - Box
    #   - [-inf, inf]
    #   - [1280]  # Flattened observation space
    #   - {}
    # policy_6:
    #   - None
    #   - Box
    #   - [-inf, inf]
    #   - [1280]  # Flattened observation space
    #   - {}
    # policy_7:
    #   - None
    #   - Box
    #   - [-inf, inf]
    #   - [1280]  # Flattened observation space
    #   - {}
    # policy_8:
    #   - None
    #   - Box
    #   - [-inf, inf]
    #   - [1280]  # Flattened observation space
    #   - {}
    # policy_9:
    #   - None
    #   - Box
    #   - [-inf, inf]
    #   - [1280]  # Flattened observation space
    #   - {}

evaluation_interval: 10
evaluation_duration: 50
evaluation_num_workers: 1
evaluation_config:
  explore: true

checkpoint_freq: 10
checkpoint_at_end: true
